# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
which0 <- function(x) {
    .Call('_fmci_which0', PACKAGE = 'fmci', x)
}

#' @export
sharpenC <- function(cp_ind, w, cval = 0.1, reach = 10L) {
    .Call('_fmci_sharpenC', PACKAGE = 'fmci', cp_ind, w, cval, reach)
}

#' @export
mergeC <- function(cp_ind, w, reach = 10L) {
    .Call('_fmci_mergeC', PACKAGE = 'fmci', cp_ind, w, reach)
}

#' @export
poolC <- function(cp_ind, reach = 10L) {
    .Call('_fmci_poolC', PACKAGE = 'fmci', cp_ind, reach)
}

#' @export
annotation_error <- function(x, y) {
    .Call('_fmci_annotation_error', PACKAGE = 'fmci', x, y)
}

#' @export
hausdorff_dist <- function(x, y) {
    .Call('_fmci_hausdorff_dist', PACKAGE = 'fmci', x, y)
}

#' @export
adjusted_rand <- function(x, y, n) {
    .Call('_fmci_adjusted_rand', PACKAGE = 'fmci', x, y, n)
}

#' @export
energydist <- function(x, y) {
    .Call('_fmci_energydist', PACKAGE = 'fmci', x, y)
}

#' @export
fmag <- function(fmat) {
    .Call('_fmci_fmag', PACKAGE = 'fmci', fmat)
}

#' @export
fmean <- function(fmat) {
    .Call('_fmci_fmean', PACKAGE = 'fmci', fmat)
}

#' @export
ftv <- function(fmat) {
    .Call('_fmci_ftv', PACKAGE = 'fmci', fmat)
}

#' @export
tv1d <- function(input, lambda) {
    .Call('_fmci_tv1d', PACKAGE = 'fmci', input, lambda)
}

